### ISSUE TITLE
能出个使用文档不

### ISSUE THREAD

**Issue by Foliga** [CD-cat/YYS_TOOL#1]

**Comment by Foliga** [comment]
已装必备的库 py版本为3.12 redis部署也没有问题 运行open.bat文件貌似出错 望指点

**Comment by CD-cat** [comment]
Open.bat是启动模拟器用的，你修改一下里面的路径，让他可以启动你的模拟器，然后后面的-clone:Nox_1删掉试试
没想到这么快有人用上，使用文档正在编写，明天可以发布，同时这个脚本还有点问题在优化，明天也会再发布一版

**Comment by Foliga** [comment]
ok 我先试试 必须支持一波

**Comment by Foliga** [comment]
> Open.bat是启动模拟器用的，你修改一下里面的路径，让他可以启动你的模拟器，后面的-clone:Nox_1替换掉试试今天 这么快有人用上，使用文档正在编写，明天可以发布，同时这个剧本还有点问题在优化，明天再发布一版
模拟器ok了 程序怎么运行呢 好兄弟 没看见启动项目呀

**Comment by CD-cat** [comment]
感谢支持，现在这个版本泛用性上还有比较大的问题，还有一些关于模拟器配置之类的设置问题啥的。。。估计暂时是用不了，等一下我明天那一版吧qwq

**Comment by CD-cat** [comment]
> ok 我先试试 必须支持一波

更新完了，你先再试试如果python3.12不行换3.8试试，

**Comment by Foliga** [comment]
我用的就是3.12 我先看看

**Comment by Foliga** [comment]
兄弟有考虑用模型来优化人为点击吗

**Comment by Foliga** [comment]
![Uploading 9F627021A249F762C386584AAD9BDAC6.png…]()

**Comment by CD-cat** [comment]
> 我用的就是3.12 我先看看

能用么？还有你发的这个图片是啥，我打不开看不了

**Comment by Foliga** [comment]
用不了 我这个缺失qt5的库 也不知道为啥 我也下载了 但还是报错

**Comment by CD-cat** [comment]
Qt相关的包用了这几个，你看下呢

![F56ROYYK~J$AOX%~60%LH{5](https://github.com/user-attachments/assets/643beb19-4be5-4faa-9284-90c8c21d4378)
![XJ{2LWCXP6RQL0@H`(YQB9](https://github.com/user-attachments/assets/58c79aca-7606-4ad5-9446-3d84e31d05ee)

**Comment by Foliga** [comment]
Traceback (most recent call last):
  File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in <module>
    import Func.FengMo
  File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in <module>
    from Func import base
  File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in <module>
    base_delay = float(r.get('base_delay').decode('utf-8'))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'decode'
兄弟要不你看看

**Comment by CD-cat** [comment]
> Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看

稍等我看看

**Comment by CD-cat** [comment]
> Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看

应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试

**Comment by Foliga** [comment]
> > Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看
> 
> 应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试

不太懂怎么操作 抱歉

**Comment by CD-cat** [comment]
> > > Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看
> > 
> > 
> > 应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试
> 
> 不太懂怎么操作 抱歉

那你等等奥，我琢磨琢磨写一个初始化模块

**Comment by Foliga** [comment]
> > > > Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看
> > > 
> > > 
> > > 应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试
> > 
> > 
> > 不太懂怎么操作 抱歉
> 
> 那你等等奥，我琢磨琢磨写一个初始化模块
好的好的 麻烦了

**Comment by CD-cat** [comment]
> > > > > Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看
> > > > 
> > > > 
> > > > 应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试
> > > 
> > > 
> > > 不太懂怎么操作 抱歉
> > 
> > 
> > 那你等等奥，我琢磨琢磨写一个初始化模块
> > 好的好的 麻烦了

ok，初始化写完了，你更新一下试试

**Comment by Foliga** [comment]
> > > > > > Traceback (most recent call last): File "D:\edgeDold\YYS_TOOL-master\Firm_Logic.py", line 7, in import Func.FengMo File "D:\edgeDold\YYS_TOOL-master\Func\FengMo.py", line 4, in from Func import base File "D:\edgeDold\YYS_TOOL-master\Func\base.py", line 17, in base_delay = float(r.get('base_delay').decode('utf-8')) ^^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'NoneType' object has no attribute 'decode' 兄弟要不你看看
> > > > > 
> > > > > 
> > > > > 应该是数据库问题，我新上传了一个前缀为Redis。。。的文件，你把那个导入一下redis试试
> > > > 
> > > > 
> > > > 不太懂怎么操作 抱歉
> > > 
> > > 
> > > 那你等等奥，我琢磨琢磨写一个初始化模块
> > > 好的好的 麻烦了
> 
> ok，初始化写完了，你更新一下试试

我一直以为你没回复我 我现在试一下

**Comment by Foliga** [comment]
可以了 好兄弟 我再研究研究模拟器配置

**Comment by CD-cat** [comment]
> 可以了 好兄弟 我再研究研究模拟器配置

好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配

**Comment by Foliga** [comment]
> > 可以了 好兄弟 我再研究研究模拟器配置
> 
> 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配

mumu12

**Comment by CD-cat** [comment]
> > > 可以了 好兄弟 我再研究研究模拟器配置
> > 
> > 
> > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> 
> mumu12

ok

**Comment by CD-cat** [comment]
> > > 可以了 好兄弟 我再研究研究模拟器配置
> > 
> > 
> > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> 
> mumu12

之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用

**Comment by Foliga** [comment]
> > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > 
> > > 
> > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > 
> > 
> > mumu12
> 
> 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用

ok 怎么看adb地址呢

**Comment by Foliga** [comment]
> > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > 
> > > 
> > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > 
> > 
> > mumu12
> 
> 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
adb配好运行显示如下
模拟器已启动，虚拟机开机未完成
模拟器已启动，虚拟机开机未完成

**Comment by CD-cat** [comment]
> > > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > > 
> > > > 
> > > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > > 
> > > 
> > > mumu12
> > 
> > 
> > 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
> > adb配好运行显示如下
> > 模拟器已启动，虚拟机开机未完成
> > 模拟器已启动，虚拟机开机未完成

等会奥，我研究一下mumu的adb操作
差不多了，mumu的adb弄明白了，不过自动开启模拟器功能暂时用不了，需要后面专项优化，你看一眼文档，手动开启阴阳师试试呢个

**Comment by Foliga** [comment]
> > > > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > > > 
> > > > > 
> > > > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > > > 
> > > > 
> > > > mumu12
> > > 
> > > 
> > > 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
> > > adb配好运行显示如下
> > > 模拟器已启动，虚拟机开机未完成
> > > 模拟器已启动，虚拟机开机未完成
> 
> 等会奥，我研究一下mumu的adb操作 差不多了，mumu的adb弄明白了，不过自动开启模拟器功能暂时用不了，需要后面专项优化，你看一眼文档，手动开启阴阳师试试呢个

好的我现在试试

**Comment by Foliga** [comment]
> > > > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > > > 
> > > > > 
> > > > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > > > 
> > > > 
> > > > mumu12
> > > 
> > > 
> > > 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
> > > adb配好运行显示如下
> > > 模拟器已启动，虚拟机开机未完成
> > > 模拟器已启动，虚拟机开机未完成
> 
> 等会奥，我研究一下mumu的adb操作 差不多了，mumu的adb弄明白了，不过自动开启模拟器功能暂时用不了，需要后面专项优化，你看一眼文档，手动开启阴阳师试试呢个

用不了 好兄弟

**Comment by CD-cat** [comment]
> > > > > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > > > > 
> > > > > > 
> > > > > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > > > > 
> > > > > 
> > > > > mumu12
> > > > 
> > > > 
> > > > 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
> > > > adb配好运行显示如下
> > > > 模拟器已启动，虚拟机开机未完成
> > > > 模拟器已启动，虚拟机开机未完成
> > 
> > 
> > 等会奥，我研究一下mumu的adb操作 差不多了，mumu的adb弄明白了，不过自动开启模拟器功能暂时用不了，需要后面专项优化，你看一眼文档，手动开启阴阳师试试呢个
> 
> 用不了 好兄弟

mumu需要每次打开模拟器之后手动链接一下adb
再CMD里面输入这个指令“adb connect 127.0.0.1:XXXXX ”XXXXX是ADB调试端口，查端口看下这篇https://mumu.163.com/help/20230214/35047_1073151.html
你再试试

**Comment by CD-cat** [comment]
> > > > > > > 可以了 好兄弟 我再研究研究模拟器配置
> > > > > > 
> > > > > > 
> > > > > > 好好好，你用的什么模拟器？我正好顺便研究一下非夜神模拟器的适配
> > > > > 
> > > > > 
> > > > > mumu12
> > > > 
> > > > 
> > > > 之前落了个东西，你看一眼新版本，有一个txt需要写入自己的ADB地址，改了那个才可以正常使用
> > > > adb配好运行显示如下
> > > > 模拟器已启动，虚拟机开机未完成
> > > > 模拟器已启动，虚拟机开机未完成
> > 
> > 
> > 等会奥，我研究一下mumu的adb操作 差不多了，mumu的adb弄明白了，不过自动开启模拟器功能暂时用不了，需要后面专项优化，你看一眼文档，手动开启阴阳师试试呢个
> 
> 用不了 好兄弟

兄弟，能用了么？我的建议是别用了，我在mumu模拟器被检测出来了，你要么换模拟器要么别用了
